# Generated by Django 2.2a1 on 2019-03-28 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0052_auto_20190311_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverrun',
            name='status',
            field=models.CharField(choices=[('starting', 'starting'), ('running', 'running'), ('shutting down', 'shutting down'), ('stopped', 'stopped'), ('Error deployment', 'error deploy'), ('sleeping', 'sleeping')], default='starting', max_length=20),
        ),
    ]
